services:
    openspeedtest:
        environment:
            CHANGE_CONTAINER_PORTS: ENC[AES256_GCM,data:v94kBw==,iv:qkA9caPPdvUvJI8frjMIB6lo84BtOLQjWOjJ3Tq+X4E=,tag:2xCLn/xB3Dof4LY0sJq4hQ==,type:str]
            HTTP_PORT: ENC[AES256_GCM,data:nPxMOYg=,iv:jSmyHXKoE1nVBgkIAAqoku6e3NjloUaLuN+GqapRxy4=,tag:7miGLAepwtg2crKwvDDh1A==,type:int]
        image: ENC[AES256_GCM,data:WEOLWyqhYc1WC9PIR174cdC0G33MUOYID29e,iv:3CSbnfVNJLzE+/sP6B02Goujos5mr42MpTc4Y4vZHh8=,tag:oTArIlE+HAcvEymwRB1gTQ==,type:str]
        labels:
            traefik.enable: ENC[AES256_GCM,data:rXrj1g==,iv:nxxkeHs8xKNcwa0zSwTSW1S94nPSt26lSSdDbBoS1Fs=,tag:79fp05Ia3/+xvUNh0ae8ig==,type:str]
            traefik.http.middlewares.openspeedtest-buffering.buffering.maxrequestbodybytes: ENC[AES256_GCM,data:G08vZGan5Z4=,iv:0Wz5fqnRqMtY8rYqgwuOAMn+lEBbArNVtJejOxFhQe8=,tag:WNQvYvxhFj7i11Ec5tLZEA==,type:str]
            traefik.http.routers.openspeedtest-http.entrypoints: ENC[AES256_GCM,data:QyVG,iv:rFELeuYyDmmCoTnw+v28UdnSqyjj2qM8ftfmjCOR2nw=,tag:Q9xssvXFeaTPdnoAHKViww==,type:str]
            traefik.http.routers.openspeedtest-http.middlewares: ENC[AES256_GCM,data:pPGy+wiSmDd85Ju1NOI4og4jcBW57lirPHpwcULabblIaBeRkzD/kRn79z0i,iv:9dQ71wZHTCqwh6UaecBANYCuPU365DTCAmwwbIpAeoo=,tag:CF9SiyUhxnjPDvVdR76aPA==,type:str]
            traefik.http.routers.openspeedtest-http.rule: ENC[AES256_GCM,data:j3mD0izUaBuVd8M3v/5oyvv+5HHU8/t129/TasQS3j+vn0griHv5,iv:Vt8D7Yfl3POweE8BrRpXbcwKBoXriqyjsq26Vl2Rnlg=,tag:e8oiaEg7k19tKygDcYt2AQ==,type:str]
            traefik.http.routers.openspeedtest-http.service: ENC[AES256_GCM,data:VwQEyrkazGbptkNkxg==,iv:ZEj9t6a1SB672S/zWx3c2FD2xTcP9YCvZ/KCvyptSaY=,tag:qD4Zr2536XQfFhH/kGyRLQ==,type:str]
            traefik.http.routers.openspeedtest.entrypoints: ENC[AES256_GCM,data:OBEMALlZWeZs,iv:5Rq0qf+ywwy8J6btIRFyUGD+kLoL7KvrXZJkYFoSqtw=,tag:eOzsN8x3IEDaNYF+OTh/EA==,type:str]
            traefik.http.routers.openspeedtest.middlewares: ENC[AES256_GCM,data:D8ErHHIfD4KB/BN8wYlDXDcRTqIS5hPO2nzLnzDTVTcdnvf3WIEc0/vuux71QalwYJA1,iv:WzzkgeVb5xtdZbl1raZbye86d9f5A+gjMpDmxyEELq8=,tag:iiX39Bt/X1e/tTRdjlF3LA==,type:str]
            traefik.http.routers.openspeedtest.rule: ENC[AES256_GCM,data:L+iZpTdSlDWLtkewHxGy82MFLjgYUrrGGxzF80esCntfiNfhD3VS,iv:HfcGLeFulB9W9Pn1u7BZXebyKnij3Z7BoWehVddsnWY=,tag:y1zzlE3z55bX9dDJZbMKmQ==,type:str]
            traefik.http.routers.openspeedtest.service: ENC[AES256_GCM,data:7biiYcyCoE33LSIayA==,iv:Oy52CGtnOXlvNkldMTIJZp7PT/iao0khR2sxkhqa+VI=,tag:vIdrppGh3JJFFgHfjDG5ww==,type:str]
            traefik.http.routers.openspeedtest.tls.certresolver: ENC[AES256_GCM,data:uDpi16n7tJUOtA==,iv:QD4MrEphc7m3X6xiR0BU9jm4pMgz+f/XyT+y5uEEQM8=,tag:MeuTDo5sTrK1cQGFs2NDWQ==,type:str]
            traefik.http.services.openspeedtest.loadbalancer.server.port: ENC[AES256_GCM,data:mF3/xMw=,iv:RSt0gL6369z3UtZzrMa6gatdtqxwNv4WW6bYaSY69fo=,tag:eN/M/jfRsMXyx6IqCS7dPA==,type:str]
        restart: ENC[AES256_GCM,data:y+dRdsWqerWWxkfBAdI=,iv:67zFunoyQOCiA4VQnz5D/fqKc4lh9HNEVISx+TtTbFY=,tag:XcENR13Y7s7ABlu03hrmwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSk8wR01SVG5wTURlVTJh
            MER5VGVRQzY4a3FWOWZ6UGVPYmE3S3UwZ0ZFCmxteFRFT3RrenZFUzFqUHVuSUJr
            VjJCMDhTUzNqU3d1Wmg4YllMaWR4SG8KLS0tIGgwUzlKM29rSytRQkJnZk5xMnlT
            T29LcG96NGRuYUVwZHZDUHJabXh4MlkKiu9WIxRAus1NHX8dapA6BPUd/QPfzbAu
            M73fstnjACpDhWL01IjLp7dkOzusKHzCX1NHsUiOMcP5zNjr3SN17A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
    lastmodified: "2026-07-19T10:27:29Z"
    mac: ENC[AES256_GCM,data:coxHNfxlbOdSLATGJ5IDYCdqEp/1AetnqhRiIYxk/merOOMOkGa2RQLFApeArmWapqKdCZw7ZvWQGvGGGKS8rWreI60mhwRlffld1nFFFADlg2BBVJRiYMCBpxc/7gluOCHyWPsj97l97+YjtgAeN9pdhJnNQBanvkoVzAzZWeg=,iv:KYU9Cszv1tewUz+vlRRHgrp+QN+2EcJ6y1c+T978SKg=,tag:P4i4IUxBdc5l46+A3G2zbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
