"creation_rules":
- "age": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
  "path_regex": "^[^/]+\\.toml$"
- "age": "age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268"
  "path_regex": "^traefik-au-hsp/"
