[[server]]
description = "HSP"
name = "au-hsp"

[server.config]
address = "http://hsp.au.excloo.dev:8120"
enabled = true
passkey = "D72vmZpmdLTvYCpQS3R0X2n6ROgTozrw"
region = "au"
[[server]]
description = "TrueNAS (AU)"
name = "au-truenas"

[server.config]
address = "https://periphery:8120"
enabled = true
passkey = "fWgCf7hboeOQqOFt6E8TS23nuNj4UWH9"
region = "au"
