[[server]]
description = "HSP"
name = "au-hsp"

[server.config]
address = "http://hsp.au.excloo.dev:8120"
enabled = true
passkey = "D72vmZpmdLTvYCpQS3R0X2n6ROgTozrw"
region = "au"
[[server]]
description = "TrueNAS (AU)"
name = "au-truenas"

[server.config]
address = "http://truenas.au.excloo.dev:8120"
enabled = true
passkey = "h0Oh9t2Jei2J8wvTze2QeEdkcbuEBAHJ"
region = "au"
