secrets:
    dozzle_cert:
        file: ENC[AES256_GCM,data:zzbxJvohO099Gmx9yHs3GTg=,iv:tqGcGJemBfpGs5h6Cw4Ip9g0TZMJHG2fZtNH7O1ksfw=,tag:cf6QNYungq/yPP803VXqow==,type:str]
    dozzle_key:
        file: ENC[AES256_GCM,data:6AQgHVZsP9sLNSg3W7jzYw==,iv:SadSZSqlNCGNrGv4xo5KBpQR/Tam6srHgYrjPYA0+gg=,tag:mizsBNYG8sSCR6TXnmRiZg==,type:str]
services:
    dozzle-agent:
        command: ENC[AES256_GCM,data:VLGFk3o=,iv:7XKtSUFhy2CKtISYi1ZgutIOhaysHkvc3b+oMiX3Fm0=,tag:GhAkX04dNpGJivujaXzJBA==,type:str]
        environment:
            DOZZLE_HOSTNAME: ENC[AES256_GCM,data:SlwD1jfH,iv:b+MaYio2bIX4Z28hQvJW1i3+uUWL1kHTbeLhdnaXvQ4=,tag:kiRT7OxWB3eZI/bWOiPI4w==,type:str]
        image: ENC[AES256_GCM,data:r3LlFOLlrfNbHOKusJ+OKYqM92Qb5g==,iv:SjtCS9x6du2dLSbnkp5cYawhJ1pL0sXCVmWO6LPxfX4=,tag:mGsACd0trIgMMKuLqVLwNw==,type:str]
        ports:
            - ENC[AES256_GCM,data:l7S+Q5Q0ecfc,iv:CuaaEz7I8bFyidbscrkkvvBO0CZ/ewQtZGy1CnU6kEU=,tag:p6Cu1NnpqP1QU/kB6xxCyA==,type:str]
        restart: ENC[AES256_GCM,data:gxeAjZ2Jq79n+qaBJ5o=,iv:JyOdZDGlHSgPsAaLHatGPElegWWkjYRhqNBD59Fl0uk=,tag:ZISj1vCTfqz1bqzEPV9lMw==,type:str]
        secrets:
            - source: ENC[AES256_GCM,data:qZmh8yoqFR/zkiE=,iv:+yN3I8YlfX2XoklqROKdpVlm9xYPK63rjimqKaN+nSQ=,tag:3wY4dJDZ8F9OT9etmdGSSQ==,type:str]
              target: ENC[AES256_GCM,data:77oJxGrl15BuUqw8ooPsQw==,iv:Td6KPti82JQUzq4c69f06UNsmj+UXXX0dnmfO2Da5IM=,tag:p1vBwn6IjZokOdUXV6mXtw==,type:str]
            - source: ENC[AES256_GCM,data:JlDjDDTORINu3w==,iv:B9f2tMmuEBcNaXiQh7Mi04Slr9zW8uP8weIqfTNczN0=,tag:U2Y7JcfZFX81i1TW/8y1fQ==,type:str]
              target: ENC[AES256_GCM,data:DwTZvBA3VQ6YzDiwTxNY,iv:ljKmCH37YniWar35hYksW3ekluA+XZCgfqjEaGU1ms8=,tag:xjurjGp1bNULm5zcUeSBMQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:0fHbzjVDIJT+DWrlgVkR5RM0z721hbGz9P+9qtaoZXlq1grTq/Q4I8MRxWI=,iv:3Vt7S0bIOZlcRo/buihlkhE2CDd/9SP693bhmUfv9yo=,tag:RfCTW/0JpmcD5b9i2/MBKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvblYxalg2M0VQU0I5aE5T
            MWQ4dy9rMUd5U0ozSXYzSWZzclY1a21TT0MwCnVBVzJVaEo4K1kydSt4cUF6Vnlj
            ZG9jU0l4MStDOFQwZ1czSUxuMGswczQKLS0tIFhvMk9TYnJsek5nT2dTQ0FqTkFL
            U2prYzl2bzNTSnRaZENJelpsQUtpblEKe0olQvKuRV6eOR6OreZ/BkhgOyFTF7R5
            uR3rCC+tgAmErPzM+3b4Rj2TiOHgPFHMJJIb1fS2QBEszpZvpZpOjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
    lastmodified: "2026-07-19T04:05:54Z"
    mac: ENC[AES256_GCM,data:8gihJuipEG+xUMx0NXMN2Qro1fVallUerK0/RWc+P+S7h0L4MWEBYS9h+/ASIozedBH2Nh00oYODejaw6psFp4xniAni/JT2M0gXYpTecEE1mHuu0NkCEeoiFrXYUqaOvRza1FrgDWJW/xdNEPR0Yx03IeeGzObzWkRNEEqohvE=,iv:Fg6BGOjowgxhcSb0Wv6tdIDBK7ZwlgBX3H31fCc1f4w=,tag:Bhs9g/fFJ4VqZbLL0c3aEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
